# Site settings
# in the templates available like {{ site.myvariable }}.
title: Clean portfolio theme for Jekyll powered by Bootstrap 4.
email: your-email@domain.com
brand: Welcome To The Blog of ye_superstar
headline: 个人简历, 学习工作 and 生活百态
description: > # this means to ignore newlines until "baseurl:"
  New Site
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://example.com" # the base hostname & protocol for your site
copyright: 精彩的人生从活出自我开始

# Build settings
markdown: kramdown

# Account ids
snapwidget: 247552

# Contacts
email: 254066080@qq.com
phone: （+86）182-5069-7643

# Tracking
googleAnalitycsID: UA-83933844-1

